ReservePJ/ReservePJ/urls.py
"""
Definition of urls for ReservePJ.
"""
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# メールをコンソールに表示する
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

ReservePJ/register/urls.py
from django.urls import path, include
from . import views
#from reserve.views import ReserveSeats

app_name = 'register'
urlpatterns = [
    #path('', views.Top.as_view(), name='top'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),
    path('reserve_seats/', views.ReserveSeats.as_view(), name='reserve_seats'),
    path('reserve_update/<int:pk>/', views.ReserveUpdate.as_view(), name='reserve_update'),
    #path('reserve_change/', views.ReserveChange, name='reserve_change'),
    path('', views.WeekWithScheduleCalendar.as_view(), name='top'),
    path('week/<int:year>/<int:month>/<int:day>/', views.WeekWithScheduleCalendar.as_view(), name='top'),
]

ReservePJ/reserve/urls.py
from django.urls import path
from . import views

ReservePJ/register/models.py
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone


class CustomUserManager(UserManager):
    """ユーザーマネージャー"""
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=150, blank=True)
    image = models.ImageField(upload_to="image", null=True, blank=True,verbose_name='プロフィール画像')
    profile = models.TextField(blank=True, default = '',verbose_name='プロフィール')

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """Return the first_name plus the last_name, with a space in
        between."""
        full_name = '%s %s' % (self.last_name, self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.get_full_name

class Day_of_the_week(models.Model):
    name_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=150,verbose_name='曜日')

    def __str__(self):
        return self.name

    def custom_name(self):
        return self.name + '曜日'

    class Meta:
        ordering = ['name_id']
        verbose_name = '曜日'
        verbose_name_plural = '曜日'

ReservePJ/register/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView,
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import Http404, HttpResponseBadRequest
from django.shortcuts import render, redirect, resolve_url
from django.template.loader import render_to_string
from django.views import generic
from django.urls import reverse_lazy
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm,EmailChangeForm,
    ReserveForm,ReserveUpdateForm,ReserveChangeForm,ReserveChangeFormSet,
)
from reserve.models import Reserve
from . import forms
from . import mixins
from .function import calc_end_time
import datetime
from django.utils import timezone


User = get_user_model()


class Top(generic.ListView):
    queryset = Reserve.objects.filter(reserve_flg= True)
    template_name = 'register/top.html'


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'register/login.html'


class Logout(LogoutView):
    """ログアウトページ"""
    template_name = 'register/top.html'

class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'register/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject = render_to_string('register/mail_template/create/subject.txt', context)
        message = render_to_string('register/mail_template/create/message.txt', context)

        user.email_user(subject, message)
        return redirect('register:user_create_done')



class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'register/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'register/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True
    def test_func(self):
        # 今ログインしてるユーザーのpkと、そのユーザー情報ページのpkが同じか、又はスーパーユーザーなら許可
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

class UserDetail(OnlyYouMixin, generic.DetailView):
    """ユーザー情報閲覧"""
    model = User
    template_name = 'register/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    """ユーザー情報更新"""
    model = User
    form_class = UserUpdateForm
    template_name = 'register/user_form.html'

    def get_success_url(self):
        return resolve_url('register:user_detail', pk=self.kwargs['pk'])


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('register:password_change_done')
    template_name = 'register/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'register/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'register/mail_template/password_reset/subject.txt'
    email_template_name = 'register/mail_template/password_reset/message.txt'
    template_name = 'register/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('register:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送りましたページ"""
    template_name = 'register/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('register:password_reset_complete')
    template_name = 'register/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワード設定しましたページ"""
    template_name = 'register/password_reset_complete.html'


class EmailChange(LoginRequiredMixin, generic.FormView):
    """メールアドレスの変更"""
    template_name = 'register/email_change_form.html'
    form_class = EmailChangeForm

    def form_valid(self, form):
        user = self.request.user
        new_email = form.cleaned_data['email']

        # URLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(new_email),
            'user': user,
        }
        
        subject = render_to_string('register/mail_template/email_change/subject.txt', context)
        message = render_to_string('register/mail_template/email_change/message.txt', context)
        send_mail(subject, message, None, [new_email])

        return redirect('register:email_change_done')


class EmailChangeDone(LoginRequiredMixin, generic.TemplateView):
    """メールアドレスの変更メールを送ったよ"""
    template_name = 'register/email_change_done.html'


class EmailChangeComplete(LoginRequiredMixin, generic.TemplateView):
    """リンクを踏んだ後に呼ばれるメアド変更ビュー"""
    template_name = 'register/email_change_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            new_email = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            User.objects.filter(email=new_email, is_active=False).delete()
            request.user.email = new_email
            request.user.save()
            return super().get(request, **kwargs)

class ReserveSeats(LoginRequiredMixin,generic.CreateView):
    """席予約"""
    model = Reserve
    form_class = ReserveForm
    template_name = 'reserve/reserve_seats.html'
 
    # form_valid関数をオーバーライドすることで、更新するフィールドと値を指定できる
    def form_valid(self, form):
        post = form.save(commit=False)
        # ログイン中のユーザーIDを隠しフォームの初期値に渡す
        post.reserve_user = self.request.user
        post.reserve_end_time = calc_end_time(post.reserve_start_time,post.reserve_hour_zone)
        # 予約済フラグにTrueをセット
        post.reserve_flg = True
        post.save()
        return redirect('register:top')  
           
class ReserveUpdate(LoginRequiredMixin,generic.UpdateView):
    """予約情報更新"""
    model = Reserve
    form_class = ReserveUpdateForm
    template_name = 'register/reserve_updateform.html'
    
    # ログインしているユーザが作ったもでなければアクセス不可
    def get_queryset(self):
    	# このビューで生成されるベースとなるクエリセットを取得
        base_qs = super(ReserveUpdate, self).get_queryset()
        # さらにユーザIDで絞った結果を返す。(存在しないので404が返る)
        # 条件分岐してエラーページを出しても可
        return base_qs.filter(reserve_user=self.request.user)

    # Formにpkを渡す（更新対象特定の値として）
    def get_form_kwargs(self):
        kwargs = super(ReserveUpdate,self).get_form_kwargs()
        kwargs['reserve_id'] =self.kwargs['pk'] 
        return kwargs

    # 更新ボタン押下時 終了時間を算出してUpdate
    def form_valid(self, form):
        post = form.save()
        post = form.save(commit=False)
        post.reserve_end_time = calc_end_time(post.reserve_start_time,post.reserve_hour_zone)
        post.save()
        return redirect('register:top')  

class WeekWithScheduleCalendar(mixins.WeekWithScheduleMixin, generic.TemplateView):
    """スケジュール付きの週間カレンダーを表示するビュー"""
    template_name = 'register/top.html'
    model = Reserve
    now = timezone.localtime(timezone.now())
    date_field = 'reserve_day'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        calendar_context = self.get_week_calendar()
        context.update(calendar_context)
        return context

def ReserveChange(request):
    """未使用:理由はForms側に記載"""
    ### formSetクラスのインスタンス
    formset = ReserveChangeFormSet(request.POST or None,queryset=Reserve.objects.filter(reserve_user_id=request.user))
    print(formset.errors)
    if request.method == 'POST' and formset.is_valid():
        formset.save()
        return redirect('register:top')

    context = {
        'formset': formset  ### テンプレートにformsetを渡す
    }

    return render(request, 'register/reserve_change.html', context)

ReservePJ/register/templates/register/email_change_complete.html
{% extends "register/base.html" %}
{% block content %}
<p>
    メールアドレスを変更しました。<br>
</p>
{% endblock %}

ReservePJ/register/templates/register/email_change_form.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

ReservePJ/register/templates/register/password_change.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

ReservePJ/register/templates/register/password_change_done.html
{% extends "register/base.html" %}
{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

ReservePJ/register/templates/register/password_reset_complete.html
{% extends "register/base.html" %}
{% block content %}
<p>
    パスワード再設定を完了しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

ReservePJ/register/templates/register/password_reset_confirm.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

ReservePJ/register/templates/register/password_reset_form.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

ReservePJ/register/templates/register/reserve_seats.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST" enctype='multipart/form-data'>
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
    {{ form.media }}
</form>
{% endblock %}

ReservePJ/register/templates/register/reserve_updateform.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST" enctype='multipart/form-data'>
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
            <tr>
                <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                <td>{{ field }} {{ field.errors }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg">送信</button>
</form>
{% endblock %}

ReservePJ/register/templates/register/top.html
{% extends "register/base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <a href="{% url 'register:top' week_previous.year week_previous.month  week_previous.day %}">前週</a>
        {{ week_first | date:"Y年m月d日" }}〜{{ week_last | date:"Y年m月d日" }}
        <a href="{% url 'register:top' week_next.year week_next.month  week_next.day %}">次週</a>

        <table class="table table-bordered">
            <thead>
            <tr>
                {% for o in office_category %}
                    <th></th>
                {% endfor %}
                {% for w in week_names %}
                    <th>{{ w }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            <tr>
                {% for o in office_category %}
                    <td>{{ o }}</td>
                {% endfor %}
                {% for day in week_days %}
                    {% if now == day %}
                        <td class="table-success">
                    {% else %}
                        <td>
                    {% endif %}
                    {{ day | date:"m/d" }}
                </td>
                {% endfor %}
            </tr>
            {% for r in resultlist %}
                    <tr>
                        <td>{{ r.0.0 }}</td>
                        <td>{{ r.1.0.only_name }}</td>
                        <td>{{ r.2.0.only_name }}</td>
                        {% for schedules in week_day_schedules.values %}
                            <td>
                            {% for s in schedules %}
                                {% if s.seats == r.2.0 and s.reserve_flg == True %}
                                    {% if s.reserve_user.pk == user.pk %}
                                        <a href="{% url 'register:reserve_update' s.reserve_id %}"><img src='{{ s.reserve_user.image.url }}' width=40>:{{ s.reserve_start_time|date:"H:i" }} - {{ s.reserve_end_time|date:"H:i" }}</a><br />
                                    {% else %}
                                        <img src='{{ s.reserve_user.image.url }}' width=40>:{{ s.reserve_start_time|date:"H:i" }} - {{ s.reserve_end_time|date:"H:i" }}<br />
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                            </td>
                        {% endfor %}
                    </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>ログインをお願いします</p>
    {% endif %}
{% endblock %}

ReservePJ/register/templates/register/user_create.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST" enctype='multipart/form-data'>
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
    {{ form.media }}
</form>
{% endblock %}

ReservePJ/register/templates/register/user_create_complete.html
{% extends "register/base.html" %}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'register:login' %}">ログイン</a>
</p>
{% endblock %}

ReservePJ/register/templates/register/user_create_done.html
{% extends "register/base.html" %}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
</p>
{% endblock %}

ReservePJ/register/templates/register/user_form.html
{% extends "register/base.html" %}
{% block content %}
<form action="" method="POST" enctype='multipart/form-data'>
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg" >送信</button>
    {{ form.media }}
</form>
{% endblock %}